### ISSUE TITLE
fix: What's the license of the generated code?

### ISSUE THREAD

**Issue by fischerscode** [VeryGoodOpenSource/very_good_dart_cli#118]
**Description**
When generating a cli package, there is no `LICENSE` file generated.
- What's the license of the generated code?
- Do I have to add any copyright notices? (Can't find any...)
- Am I allowed to remove the `Generated by the [Very Good CLI][very_good_cli_link] 🤖` from the `README.md`?

**Steps To Reproduce**

1. Run `very_good create dart_cli my_cli`

**Expected Behavior**
I'd expect some kind of license information, or at least let the command tell me about the conditions.

**Screenshots**
N/A

**Additional Context**
As far as I know, a missing license information means, that I'm not allowed to do anything with the generated code.

**Comment by tomarra** [comment]
Hi @fischerscode, thanks for asking this question!

Overall, while the generator is covered by the MIT License the code that it generates is actually free to use and apply whichever license you see fit for your project. This is not unlike the Flutter project generator as well. When you run a brand new `flutter create` you get a code base but there is no license applied to it at that time. It's best practice to add a LICENSE file, like you see in our sample repo's like https://github.com/VGVentures/flame_behaviors_pong_example. 

As far as the copyright on the files and README, we typically ask that those stick around to give proper attribution to the tools used to create the codebase but obviously that is up to you given the needs of your project.
